'use strict';
SC.validateConfig = function(input){const out={...SC.defaults};if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('환경 설정은 JSON 객체여야 합니다.');
  const enums={terrain:['flat','uphill','downhill','rolling','stairs'],density:['none','few','many'],light:['sun','artificial','low'],quality:['high','low']};
  const ranges={slope:[2,12],sunElevation:[8,85],sunAzimuth:[0,360],followDistance:[1.1,3.5],maxSpeed:[.3,1.5],userSpeed:[.35,1.5],cargo:[0,65],seed:[1,9999999],lidarRange:[4,12],uwbRange:[6,30],uwbFov:[120,180],tofRange:[1,4],noise:[0,2],peopleSpeed:[.2,1.2],boxMass:[2,20]};
  for(const [k,v]of Object.entries(input)){if(!(k in out))continue;if(k in enums){if(!enums[k].includes(v))throw new Error('잘못된 설정: '+k);out[k]=v;}else if(k in ranges){if(typeof v!=='number'||!Number.isFinite(v)||v<ranges[k][0]||v>ranges[k][1])throw new Error('범위를 벗어난 설정: '+k);out[k]=k==='seed'?Math.floor(v):v;}else if(typeof out[k]==='boolean'){if(typeof v!=='boolean')throw new Error('잘못된 스위치: '+k);out[k]=v;}}
  return out;
};
SC.Simulation = class Simulation {
  constructor(config={}){this.config=SC.validateConfig(config);this.world=new SC.World(this.config);this.sensors=new SC.Sensors(this.config);this.nav=new SC.Navigation(this.config,this.world);this.time=0;this.tick=0;this.paused=false;this.estop=false;this.input={x:0,z:0};this.contactUntil=0;this.contacts=0;this.events=[];this.samples=[];this.inputLog=[];this.lastLog=-1;this.state='ACQUIRE';this.command={speed:0,steer:0,brake:true};
    this.cart={x:0,y:0,z:-6.1,yaw:0,pitch:0,roll:0,v:0,a:0,steer:0,steerL:0,steerR:0,spinL:0,spinR:0,spinFL:0,spinFR:0,rpmL:0,rpmR:0,currentL:0,currentR:0,powerL:0,powerR:0,torqueL:0,torqueR:0,dutyL:0,dutyR:0,brake:true,voltage:24,distance:0,brakeW:0};this.user={x:0,y:0,z:-2.7,vx:0,vz:0,yaw:0,phase:0,r:.25};this.cart.y=this.world.height(this.cart.x,this.cart.z);this.user.y=this.world.height(this.user.x,this.user.z);this.history={};this.sensors.update(this.world,this.cart,this.user,0);this.nav.observe(this.sensors,0,this.cart);this.nav.plan(this.world,this.cart,this.sensors,0);this.recordEvent('SYSTEM','시뮬레이션 시작. 센서·전류·제동은 모의값입니다.');}
  setInput(x,z){if(!Number.isFinite(x)||!Number.isFinite(z))return;const n=Math.max(1,Math.hypot(x,z));this.input={x:x/n,z:z/n};if(this.inputLog.length<72000)this.inputLog.push({t:this.time,x:this.input.x,z:this.input.z});}
  setEmergency(value){this.estop=!!value;if(value){this.recordEvent('E_STOP','비상정지 래치. 시뮬레이션 제동 적용.');}else{this.recordEvent('RESET','비상정지 해제. 센서와 경로를 다시 확인합니다.');this.nav.lastPlan=-1;}}
  recordEvent(type,message){this.events.unshift({t:this.time,type,message});if(this.events.length>120)this.events.pop();}
  step(dt=SC.constants.step){if(this.paused)return;dt=SC.math.clamp(dt,.001,.04);this.time+=dt;this.tick++;this.world.userMove(this.user,this.input.x*this.config.userSpeed,this.input.z*this.config.userSpeed,dt);this.world.step(dt,this.user,this.cart);
    const fresh=this.sensors.update(this.world,this.cart,this.user,this.time);if(fresh)this.nav.observe(this.sensors,this.time,this.cart);
    if(this.tick%3===0){this.command=this.nav.command(this.world,this.cart,this.sensors,this.time);if(this.estop){this.command={speed:0,steer:this.cart.steer,brake:true};this.nav.status='E_STOP';}else if(this.time<this.contactUntil){this.command={speed:0,steer:this.cart.steer,brake:true};this.nav.status='CONTACT_HOLD';}}
    this.integrate(dt);if(this.nav.status!==this.state){this.state=this.nav.status;this.recordEvent('STATE',this.state);}
    if(this.time-this.lastLog>=.1-1e-8){this.capture();this.lastLog=this.time;}
  }
  integrate(dt){const c=this.cart,K=SC.constants,{clamp,lerp}=SC.math,cmd=this.estop?{speed:0,steer:c.steer,brake:true}:this.command,old={x:c.x,z:c.z,yaw:c.yaw,v:c.v};
    Object.assign(c,SC.cartTerrainPose(c,this.world));
    c.steer+=clamp(cmd.steer-c.steer,-1.15*dt,1.15*dt);
    const curvature=Math.tan(c.steer)/K.wheelbase;
    c.steerL=Math.atan(K.wheelbase*curvature/(1+K.frontTrack*curvature/2));c.steerR=Math.atan(K.wheelbase*curvature/(1-K.frontTrack*curvature/2));
    const motion=SC.longitudinalStep(c,cmd,this.config,dt),mass=motion.mass;
    let travel=motion.distance,force=motion.force;
    // Signed surface travel is projected onto the horizontal planning plane.
    const groundTravel=travel*Math.cos(c.pitch),dyaw=groundTravel*curvature;
    c.x+=Math.sin(c.yaw+dyaw/2)*groundTravel;c.z+=Math.cos(c.yaw+dyaw/2)*groundTravel;c.yaw=SC.math.wrap(c.yaw+dyaw);
    let terrainBad=false;for(const x of [-K.halfWidth,K.halfWidth])for(const z of [K.bodyOffset-K.halfLength,K.bodyOffset+K.halfLength]){let xx=c.x+x*Math.cos(c.yaw)+z*Math.sin(c.yaw),zz=c.z-x*Math.sin(c.yaw)+z*Math.cos(c.yaw);if(!this.world.allowed(xx,zz,.03))terrainBad=true;}
    if(terrainBad){c.x=old.x;c.z=old.z;c.yaw=old.yaw;c.v=0;travel=0;force=0;c.motorForce=0;c.speedIntegralN=0;c.speedReference=0;c.brake=true;this.nav.status='TERRAIN_HOLD';}
    let contacted=null;for(const o of [...this.world.objects,{...this.user,id:'tag-user',type:'person',r:.25}]){let collide=false;
      if(o.type==='box'){ // SAT: oriented cart rectangle against an axis-aligned movable box.
        const cc={x:c.x+Math.sin(c.yaw)*K.bodyOffset,z:c.z+Math.cos(c.yaw)*K.bodyOffset},dx=o.x-cc.x,dz=o.z-cc.z,co=Math.cos(c.yaw),si=Math.sin(c.yaw);
        collide=Math.abs(dx*co-dz*si)<K.halfWidth+Math.abs(co)*o.w/2+Math.abs(si)*o.d/2&&Math.abs(dx*si+dz*co)<K.halfLength+Math.abs(si)*o.w/2+Math.abs(co)*o.d/2&&Math.abs(dx)<o.w/2+Math.abs(co)*K.halfWidth+Math.abs(si)*K.halfLength&&Math.abs(dz)<o.d/2+Math.abs(si)*K.halfWidth+Math.abs(co)*K.halfLength;
      }else collide=this.world.localRectDistance(o.x,o.z,c)<o.r;
      if(collide){contacted=o;break;}}
    if(contacted){if(Math.abs(old.v)>.005||this.time>this.contactUntil){this.contacts++;this.recordEvent('CONTACT',contacted.type==='box'?'상자 접촉. 충격량을 상자에 전달하고 정지합니다.':'접촉 감지. 시뮬레이션 안전 정지.');}
      if(contacted.type==='box'){let J=Math.min(6,Math.abs(old.v)*1.08*(mass*contacted.mass)/(mass+contacted.mass));contacted.vx+=Math.sin(c.yaw)*Math.sign(old.v)*J/contacted.mass;contacted.vz+=Math.cos(c.yaw)*Math.sign(old.v)*J/contacted.mass;}
      c.x=old.x;c.z=old.z;c.yaw=old.yaw;c.v=0;travel=0;force=0;c.motorForce=0;c.speedIntegralN=0;c.speedReference=0;c.brake=true;this.contactUntil=this.time+.65;this.nav.status='CONTACT_HOLD';this.nav.lastPlan=-1;
    }
    const vl=c.v*(1+curvature*K.rearTrack/2),vr=c.v*(1-curvature*K.rearTrack/2),omegaL=vl/K.rearRadius,omegaR=vr/K.rearRadius;c.rpmL=omegaL*30/Math.PI;c.rpmR=omegaR*30/Math.PI;c.spinL+=travel*(1+curvature*K.rearTrack/2)/K.rearRadius;c.spinR+=travel*(1-curvature*K.rearTrack/2)/K.rearRadius;c.spinFL+=travel/Math.max(.1,Math.cos(c.steerL))/K.frontRadius;c.spinFR+=travel/Math.max(.1,Math.cos(c.steerR))/K.frontRadius;
    for(const side of ['L','R']){let speed=side==='L'?vl:vr,omega=speed/K.rearRadius,ratio=Math.abs(c.v)>.01?clamp(speed/c.v,.3,1.7):1,torque=c.brake?0:force*K.rearRadius*.5,power=Math.max(0,torque*omega),current=c.brake||c.coasting?0:.45+Math.abs(torque)*.14+power/(24*.78);c['torque'+side]=torque;c['power'+side]=power;c['current'+side]=current;c['duty'+side]=c.brake||c.coasting?0:clamp(speed/(K.noLoadRPM*Math.PI/30*K.rearRadius)*100+torque/24*22,-100,100);}
    c.voltage=24-.035*(c.currentL+c.currentR);c.distance+=Math.abs(travel);c.a=(c.v-old.v)/dt;Object.assign(c,SC.cartTerrainPose(c,this.world));
  }
  capture(){const c=this.cart,s=this.sensors,u=s.uwb.fused,o=s.origin(c,[0,.858,.824]),distance=u?Math.hypot(u.x-o[0],u.z-o[2]):null;let sample={t:+this.time.toFixed(3),state:this.state,cart_x:c.x,cart_z:c.z,cart_yaw_deg:c.yaw/SC.math.DEG,user_x:this.user.x,user_z:this.user.z,estimated_user_x:u?.x??null,estimated_user_z:u?.z??null,uwb_fused_m:distance,uwb_left_m:s.uwb.anchors[0]?.distance??null,uwb_right_m:s.uwb.anchors[1]?.distance??null,uwb_quality:s.uwb.quality,uwb_age_s:this.time-s.uwb.stamp,lidar_nearest_m:s.lidar.nearest,lidar_hits:s.lidar.hits,lidar_quality:s.lidar.quality,tof_left_m:s.tof.values[0]?.distance??null,tof_right_m:s.tof.values[1]?.distance??null,speed_mps:c.v,command_speed_mps:this.command.speed,rpm_left:c.rpmL,rpm_right:c.rpmR,current_left_A:c.currentL,current_right_A:c.currentR,power_left_W:c.powerL,power_right_W:c.powerR,torque_left_Nm:c.torqueL,torque_right_Nm:c.torqueR,duty_left_pct:c.dutyL,duty_right_pct:c.dutyR,steer_left_deg:c.steerL/SC.math.DEG,steer_right_deg:c.steerR/SC.math.DEG,command_steer_deg:this.command.steer/SC.math.DEG,pitch_deg:c.pitch/SC.math.DEG,brake:c.brake,brake_W:c.brakeW,acceleration_mps2:c.a,gravity_force_N:c.gravityForce??0,motor_force_N:c.motorForce??0,rolling_force_N:c.rollingForce??0,brake_force_N:c.brakeForce??0,effective_mass_kg:c.effectiveMass??(SC.dynamics.massKg+this.config.cargo+2*SC.dynamics.rearInertia/SC.constants.rearRadius**2+2*SC.dynamics.frontInertia/SC.constants.frontRadius**2),parking_brake:!!c.parking,contacts:this.contacts};
    this.samples.push(sample);if(this.samples.length>18000)this.samples.shift();for(const [k,v]of Object.entries(sample))if(typeof v==='number'||v===null){if(!this.history[k])this.history[k]=[];this.history[k].push(v);if(this.history[k].length>120)this.history[k].shift();}this.latest=sample;
  }
  telemetry(){const c=this.cart,s=this.sensors,u=s.uwb.fused,ok=u&&this.time-s.uwb.stamp<.75,origin=s.origin(c,[0,.858,.824]);return{t:Math.round(this.time*1000),link:{state:'simulation',rtt_ms:0},power:{battery_v:c.voltage,battery_pct:null,contactor:this.estop?'open':'closed',estop:this.estop},drive:{mode:'follow',duty_l:c.dutyL,duty_r:c.dutyR,current_l:c.currentL,current_r:c.currentR,speed_mps:c.v},pose:{roll:c.roll/SC.math.DEG,pitch:c.pitch/SC.math.DEG,yaw:c.yaw/SC.math.DEG},lidar:{seq:s.lidar.seq,start_deg:0,step_deg:360/s.lidar.rays.length,ranges_mm:s.lidar.rays.map(r=>r.valid&&r.hit?Math.round(r.distance*1000):0)},tof:{left_mm:s.tof.values[0]?.distance==null?null:Math.round(s.tof.values[0].distance*1000),right_mm:s.tof.values[1]?.distance==null?null:Math.round(s.tof.values[1].distance*1000),cliff:null},uwb:{tag:ok?'ok':'lost',dist_m:ok?Math.hypot(u.x-origin[0],u.z-origin[2]):null,bearing_deg:ok?SC.math.wrap(Math.atan2(u.x-origin[0],u.z-origin[2])-c.yaw)/SC.math.DEG:null},faults:[...(this.estop?['E_STOP']:[]),...(this.state==='TERRAIN_HOLD'?['SIM_TERRAIN_GUARD']:[]),...Object.entries(s.fault).filter(([,v])=>v).map(([k])=>'SIM_'+k.toUpperCase()+'_OFF')],sim:{schema:'smart-cart-simulation/1',source:'synthetic',state:this.state,servo_left_deg:c.steerL/SC.math.DEG,servo_right_deg:c.steerR/SC.math.DEG,brake_assumption:'uncalibrated_finite_service_and_parking_brake',acceleration_mps2:c.a,gravity_force_N:c.gravityForce??0,motor_force_N:c.motorForce??0,brake_force_N:c.brakeForce??0,tof_mount:'forward',tof_semantic_override:true}};}
  disturbance(){const boxes=this.world.objects.filter(o=>o.type==='box');if(!boxes.length){this.recordEvent('NOTICE','상자가 없는 환경입니다. 환경 설정에서 상자를 켜세요.');return false;}boxes.sort((a,b)=>SC.math.dist(a,this.cart)-SC.math.dist(b,this.cart));const o=boxes[0],dx=this.cart.x-o.x,dz=this.cart.z-o.z,d=Math.hypot(dx,dz)||1;o.vx+=dx/d*4/o.mass;o.vz+=dz/d*4/o.mass;this.recordEvent('DISTURBANCE','가장 가까운 상자에 카트 방향 4 N·s 외란을 주입했습니다.');return true;}
};
